# Generated by Django 5.0.4 on 2024-04-30 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormulationDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeAnimal', models.CharField(max_length=3, unique=True)),
                ('nomAnimal', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeIngredient', models.CharField(max_length=9, unique=True)),
                ('nomIngredient', models.CharField(max_length=50)),
                ('proteineBrute', models.FloatField(null=True)),
                ('energieMetabolisable', models.FloatField(null=True)),
                ('matiereGrasse', models.FloatField(null=True)),
                ('celluloseBrute', models.FloatField(null=True)),
                ('calcium', models.FloatField(null=True)),
                ('phosphore', models.FloatField(null=True)),
                ('lysine', models.FloatField(null=True)),
                ('methionine', models.FloatField(null=True)),
                ('cysteineMethionine', models.FloatField(null=True)),
                ('sodium', models.FloatField(null=True)),
                ('prix', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codePays', models.CharField(max_length=3, unique=True)),
                ('nomPays', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseDeveloppement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codePhase', models.CharField(max_length=4, unique=True)),
                ('trancheAge', models.CharField(max_length=30)),
                ('nomPhase', models.CharField(max_length=30)),
                ('proteineBruteMin', models.FloatField()),
                ('proteineBruteMax', models.FloatField()),
                ('energieMetabolisableMin', models.FloatField()),
                ('energieMetabolisableMax', models.FloatField()),
                ('matiereGrasseMin', models.FloatField()),
                ('matiereGrasseMax', models.FloatField()),
                ('calciumMin', models.FloatField()),
                ('calciumMax', models.FloatField()),
                ('phosphoreMin', models.FloatField()),
                ('phosphoreMax', models.FloatField()),
                ('lysineMin', models.FloatField()),
                ('lysineMax', models.FloatField()),
                ('methionineMin', models.FloatField()),
                ('methionineMax', models.FloatField()),
                ('cysteineMethionineMin', models.FloatField()),
                ('cysteineMethionineMax', models.FloatField()),
                ('sodiumMin', models.FloatField()),
                ('sodiumMax', models.FloatField()),
                ('ratioEnergieProteineMin', models.FloatField()),
                ('ratioEnergieProteineMax', models.FloatField()),
                ('ratioCalciumPhosphoreMin', models.FloatField()),
                ('ratioCalciumPhosphoreMax', models.FloatField()),
                ('ratioLysineMethionineMin', models.FloatField()),
                ('ratioLysineMethionineMax', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeVaccin', models.CharField(max_length=3, unique=True)),
                ('nomVaccin', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCategorie', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codeAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyFeed.formulationdisponible')),
                ('idIngredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyFeed.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='codeIngredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyFeed.listeingredients'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='codePays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyFeed.pays'),
        ),
        migrations.CreateModel(
            name='PhaseActuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codeAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Phases', to='easyFeed.formulationdisponible')),
                ('codePhase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Phases', to='easyFeed.phasedeveloppement')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=7, unique=True)),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('dateNaissance', models.DateField()),
                ('dateEmbauche', models.DateField()),
                ('numeroTelephone', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codePays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyFeed.pays')),
                ('idTypeUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Type_Utilisateurs', to='easyFeed.typeutilisateur')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeRecette', models.CharField(max_length=4, unique=True)),
                ('recette', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codeAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recettes', to='easyFeed.formulationdisponible')),
                ('codePays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyFeed.pays')),
                ('matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recettes', to='easyFeed.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Vague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeVague', models.CharField(max_length=9, unique=True)),
                ('qte', models.IntegerField()),
                ('age', models.CharField(max_length=20)),
                ('masse', models.FloatField()),
                ('nomAnimal', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codePhase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vagues', to='easyFeed.phasedeveloppement')),
                ('matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vagues', to='easyFeed.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinAdministre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codeVaccin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vagues', to='easyFeed.vaccin')),
                ('codeVague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vaccins', to='easyFeed.vague')),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeSortie', models.CharField(max_length=14, unique=True)),
                ('qteSortie', models.IntegerField()),
                ('dateSortie', models.DateField()),
                ('masseSortie', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codeVague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sorties', to='easyFeed.vague')),
            ],
        ),
        migrations.CreateModel(
            name='Perte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codePerte', models.CharField(max_length=14, unique=True)),
                ('qtePerte', models.IntegerField()),
                ('dateDeces', models.DateField()),
                ('commentaires', models.CharField(max_length=600)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codeVague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pertes', to='easyFeed.vague')),
            ],
        ),
        migrations.CreateModel(
            name='EvolutionMasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouvelAge', models.IntegerField()),
                ('dateEvolution', models.DateField()),
                ('nouvelleMasse', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codeVague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Masses', to='easyFeed.vague')),
            ],
        ),
        migrations.CreateModel(
            name='VagueRecette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codeRecette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vagues', to='easyFeed.recette')),
                ('codeVague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recettes', to='easyFeed.vague')),
            ],
        ),
    ]
