# Generated by Django 5.0.4 on 2024-05-03 14:34

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyFeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listeingredients',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='categorieingredient',
            name='codeAnimal',
            field=models.ForeignKey(default='PL', on_delete=django.db.models.deletion.CASCADE, to='easyFeed.formulationdisponible'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='codePays',
            field=models.ForeignKey(default='CMR', on_delete=django.db.models.deletion.CASCADE, to='easyFeed.pays'),
        ),
    ]
