# Generated by Django 5.0.4 on 2024-05-02 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyFeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieingredient',
            name='codeAnimal',
            field=models.ForeignKey(default='PL', on_delete=django.db.models.deletion.CASCADE, to='easyFeed.formulationdisponible'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='codePays',
            field=models.ForeignKey(default='CMR', on_delete=django.db.models.deletion.CASCADE, to='easyFeed.pays'),
        ),
    ]
