# Generated by Django 5.0.4 on 2024-05-03 14:53

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyFeed', '0002_alter_listeingredients_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listeingredients',
            managers=[
                ('liste_ingredient', django.db.models.manager.Manager()),
            ],
        ),
    ]
