# Generated by Django 5.0.4 on 2024-05-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyFeed', '0003_alter_listeingredients_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listeingredients',
            managers=[
            ],
        ),
    ]
