# Generated by Django 5.0.4 on 2024-05-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyFeed', '0002_alter_categorieingredient_codeanimal_and_more'),
        ('easyFeed', '0004_alter_listeingredients_managers'),
    ]

    operations = [
    ]
