# Generated by Django 5.0.4 on 2024-05-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyFeed', '0006_client_typeabonnement_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
    ]
