# Generated by Django 5.0.4 on 2024-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyFeed', '0009_remove_client_adresse_remove_client_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='1234', max_length=128),
        ),
    ]
