# Generated by Django 5.0.4 on 2024-05-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyFeed', '0009_remove_client_adresse_remove_client_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulationdisponible',
            name='codeAnimal',
            field=models.CharField(max_length=3),
        ),
    ]
