# Generated by Django 5.0.4 on 2024-05-15 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyFeed', '0010_alter_formulationdisponible_codeanimal'),
        ('easyFeed', '0011_alter_utilisateur_password'),
    ]

    operations = [
    ]
